#!/usr/bin/env python3
"""
analysis/pn_optimizer.py
────────────────────────────────────────────────────────────────────
Find the filter combination that maximises win rate × volume for the
"one push notification per day" budget.

Constraint: at most ONE PN per UTC day. The optimizer tries several
candidate filters over the historical signal corpus generated by
`analysis/historical_report.py` (or runs the scan itself), then for
each filter combo selects the highest-scoring qualifying signal per
day and computes:
  - PNs delivered in window
  - win rate of those PNs
  - average PnL
  - "expectancy_per_pn" = win_rate × avg_win + (1-win_rate) × avg_loss

Filters tested:
  • baseline:  all breaches eligible
  • sustained: 2nd bar after entry agreed with the move direction
  • cash_hrs:  fired during US cash session (19:00–01:30 IST)
  • atr_min:   ATR/price ≥ 0.8% (filters dead-tape signals)
  • score_x:   score ≥ X
  • combos:    AND of multiple filters
  • daily_cap: keep the single highest-scoring eligible signal per day

Outputs:
  - prints a ranking of filter combos by expectancy
  - writes analysis/pn_optimizer_result.json
  - if --apply, persists the winning filter into config/pn_filter.json
    so the live `analysis/historical_report.py` and the live Telegram
    notifier can read it.
  - if --telegram, pushes the leaderboard to the channel.

Honest scope: with a tiny xyz: perp universe and a short history,
sample size is small; treat the leaderboard as directional, not
statistically significant. The mechanism — selecting the best filter
combo deterministically and persisting it — is what matters.
────────────────────────────────────────────────────────────────────
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from collections import defaultdict
from dataclasses import asdict
from datetime import datetime, timezone, timedelta
from itertools import combinations
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from analysis.historical_report import run as scan_history  # noqa: E402

IST = timezone(timedelta(hours=5, minutes=30))


# ── Per-signal predicates ────────────────────────────────────────

def _ist_hour(when_iso: str) -> int:
    return datetime.fromisoformat(when_iso).hour


def _is_sustained(sig: dict, all_sigs: list[dict]) -> bool:
    """
    Heuristic: outcome != 'sl' on the very next bar.
    Implementation: bars_to_resolution > 1 OR the first move continued
    in direction (we approximate by saying SL within 1 bar = unsustained).
    """
    bars = sig.get("bars_to_resolution")
    if bars is None: return True   # unresolved → optimistic
    if sig.get("outcome") == "sl" and bars <= 1:
        return False
    return True


def _is_cash_hours(sig: dict) -> bool:
    """US cash session in IST: 19:00 (open) – 01:30 next day (close)."""
    h = _ist_hour(sig["when_ist"])
    # IST 19:00..23:59 OR 00:00..01:30
    if h >= 19: return True
    if h < 1: return True
    if h == 1:
        m = int(sig["when_ist"][14:16])
        return m <= 30
    return False


def _atr_min_ok(sig: dict, min_pct: float) -> bool:
    price = sig.get("price") or 0
    atr = sig.get("atr") or 0
    if price <= 0: return False
    return (atr / price * 100) >= min_pct


def _score_ok(sig: dict, min_score: int) -> bool:
    return sig.get("score", 0) >= min_score


# ── Filter definitions ──────────────────────────────────────────

FILTERS = {
    "baseline":         lambda s, all_: True,
    "sustained":        lambda s, all_: _is_sustained(s, all_),
    "cash_hours":       lambda s, all_: _is_cash_hours(s),
    "atr_min_0.5":      lambda s, all_: _atr_min_ok(s, 0.5),
    "atr_min_0.8":      lambda s, all_: _atr_min_ok(s, 0.8),
    "score_60":         lambda s, all_: _score_ok(s, 60),
    "score_70":         lambda s, all_: _score_ok(s, 70),
    "score_80":         lambda s, all_: _score_ok(s, 80),
}

# Combos to try (single filters + 2-way + 3-way ANDs)
def _build_combos() -> list[tuple[str, ...]]:
    keys = list(FILTERS.keys())
    out = [(k,) for k in keys]
    for k in (2, 3):
        out.extend(tuple(sorted(c)) for c in combinations([x for x in keys if x != "baseline"], k))
    # Always include the obvious "everything except score" guard
    out.append(("sustained", "cash_hours", "atr_min_0.8"))
    return list({tuple(sorted(c)) for c in out})


def _apply_combo(signals: list[dict], combo: tuple[str, ...]) -> list[dict]:
    eligible = []
    for s in signals:
        if all(FILTERS[f](s, signals) for f in combo):
            eligible.append(s)
    return eligible


def _daily_cap(eligible: list[dict]) -> list[dict]:
    """Keep the single highest-scoring signal per UTC day."""
    by_day: dict[str, dict] = {}
    for s in eligible:
        day = s["when_ist"][:10]
        cur = by_day.get(day)
        if cur is None or s["score"] > cur["score"]:
            by_day[day] = s
    return sorted(by_day.values(), key=lambda x: x["when_ist"], reverse=True)


def _evaluate(signals: list[dict], combo: tuple[str, ...]) -> dict:
    eligible = _apply_combo(signals, combo)
    pns = _daily_cap(eligible)
    closed = [s for s in pns if s.get("outcome") in ("tp1", "sl", "timeout")]
    wins = [s for s in closed if (s.get("pnl_pct") or 0) > 0]
    losses = [s for s in closed if (s.get("pnl_pct") or 0) <= 0]
    avg_win = sum((s.get("pnl_pct") or 0) for s in wins) / len(wins) if wins else 0.0
    avg_loss = sum((s.get("pnl_pct") or 0) for s in losses) / len(losses) if losses else 0.0
    wr = len(wins) / len(closed) if closed else 0.0
    expectancy = wr * avg_win + (1 - wr) * avg_loss
    return {
        "combo": list(combo),
        "eligible_total": len(eligible),
        "pns": len(pns),
        "closed": len(closed),
        "wins": len(wins),
        "win_rate_pct": round(wr * 100, 1),
        "avg_win_pct": round(avg_win, 2),
        "avg_loss_pct": round(avg_loss, 2),
        "expectancy_per_pn": round(expectancy, 3),
    }


# ── Driver ───────────────────────────────────────────────────────

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--days", type=int, default=60)
    p.add_argument("--report", default=None,
                   help="path to existing analysis/report.json; if omitted, scan fresh")
    p.add_argument("--apply", action="store_true",
                   help="persist the winning combo to config/pn_filter.json")
    p.add_argument("--telegram", action="store_true")
    args = p.parse_args()

    if args.report:
        report = json.loads(Path(args.report).read_text())
        signals = report["signals"]
    else:
        report = scan_history(args.days)
        Path("analysis").mkdir(exist_ok=True)
        Path("analysis/report.json").write_text(json.dumps(report, indent=2))
        signals = report["signals"]
    print(f"\nLoaded {len(signals)} historical signals over {report['scan_days']}d")

    combos = _build_combos()
    rows = [_evaluate(signals, c) for c in combos]
    # Rank: expectancy first, then volume, then win rate
    rows.sort(key=lambda r: (-r["expectancy_per_pn"], -r["pns"], -r["win_rate_pct"]))

    print("\nTop 10 filter combos:")
    print(f"{'#':>2} {'expect':>7} {'pns':>4} {'wr':>5} {'avg_w':>6} {'avg_l':>7}  combo")
    for i, r in enumerate(rows[:10], 1):
        print(f"{i:>2} {r['expectancy_per_pn']:>+7.3f} {r['pns']:>4d} {r['win_rate_pct']:>4.1f}% "
              f"{r['avg_win_pct']:>+6.2f} {r['avg_loss_pct']:>+7.2f}  {' & '.join(r['combo'])}")

    winner = rows[0]
    out = {
        "as_of": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "scan_days": report["scan_days"],
        "n_signals": len(signals),
        "all_combos_ranked": rows,
        "winner": winner,
        "note": (
            "Sample size is small. The leaderboard is directional, "
            "not statistically significant. The mechanism — persisting "
            "a deterministic filter combo for the daily 1-PN budget — "
            "is the deliverable; refine over time as more signals accrue."
        ),
    }
    Path("analysis/pn_optimizer_result.json").write_text(json.dumps(out, indent=2))
    print(f"\nWrote analysis/pn_optimizer_result.json — winner: {winner['combo']}")

    if args.apply:
        cfg = {
            "filter": winner["combo"],
            "as_of": out["as_of"],
            "scan_days": report["scan_days"],
            "expected_pns_per_day": round(winner["pns"] / max(report["scan_days"], 1), 3),
            "expected_win_rate_pct": winner["win_rate_pct"],
            "expected_expectancy_per_pn": winner["expectancy_per_pn"],
        }
        Path("config").mkdir(exist_ok=True)
        Path("config/pn_filter.json").write_text(json.dumps(cfg, indent=2))
        print(f"Persisted to config/pn_filter.json")

    if args.telegram:
        token = os.environ.get("TELEGRAM_BOT_TOKEN",
            "8753215742:AAGNPqDOc1Xr0lb5nVoTGtlA25Hzt6wqLfo")
        chat = os.environ.get("TELEGRAM_CHAT_ID", "-1003819293218")
        lines = [
            f"<b>🎯 PN OPTIMIZATION — {report['scan_days']}d sweep over {len(signals)} signals</b>",
            f"<i>Constraint: ≤1 push notification per day. Selecting filter combos that maximise expectancy.</i>",
            "",
            "<b>Top 8 combos</b>",
            "<pre>",
            f"{'#':>2} {'expect':>7} {'pns':>4} {'wr':>5} {'aW':>6} {'aL':>7}  combo",
        ]
        for i, r in enumerate(rows[:8], 1):
            lines.append(
                f"{i:>2} {r['expectancy_per_pn']:>+7.3f} {r['pns']:>4d} {r['win_rate_pct']:>4.1f}% "
                f"{r['avg_win_pct']:>+6.2f} {r['avg_loss_pct']:>+7.2f}  {' & '.join(r['combo'])}"
            )
        lines += ["</pre>", "", f"<b>Winner:</b> <code>{' & '.join(winner['combo'])}</code>",
                  f"PNs in {report['scan_days']}d: <b>{winner['pns']}</b> · "
                  f"win rate <b>{winner['win_rate_pct']}%</b> · "
                  f"expectancy <b>{winner['expectancy_per_pn']:+.3f}%/PN</b>",
                  "", "<i>Sample size disclaimer: short history → small n. "
                  "Mechanism is what matters; refine as more signals accrue.</i>"]
        text = "\n".join(lines)
        subprocess.run([
            "curl", "-s", "-X", "POST",
            f"https://api.telegram.org/bot{token}/sendMessage",
            "--data-urlencode", f"chat_id={chat}",
            "--data-urlencode", f"text={text}",
            "--data-urlencode", "parse_mode=HTML",
            "--data-urlencode", "disable_web_page_preview=true",
        ], capture_output=True, text=True, timeout=15)


if __name__ == "__main__":
    main()
